### ISSUE TITLE
Why is context.Context not used?

### ISSUE THREAD

**Issue by kulak** [pitr/gig#10]
### Issue Description

Context interface Set function signature is 

    Set(key string, val interface{})

that signature is not safe for client level code to use.  

For example, library uses keyword "subject" and this keyword will collide if client level code will use "subject" as well.

Standard GO `context` will not suffer from this issue if used correctly, because `context.WithValue` uses interface for the key.

The proper use is demonstrated here:  <https://stackoverflow.com/questions/39946583/how-to-pass-context-in-golang-request-to-middleware>.

**Comment by pitr** [comment]
Thanks @kulak, that's very valid. Would you be able to try to convert `git.Context` to implement `context.Context` in a PR?

**Comment by kulak** [comment]
I kind of solved the problem with creation of library that copies net/http interface: https://github.com/kulak/gemini
