### ISSUE TITLE
Virtual hosting

### ISSUE THREAD

**Issue by makeworld-the-better-one** [pitr/gig#2]
It doesn't look like there's any way to specify a domain name when running Gig, it'd be nice to be able to do that. And then to have multi-host support, so certain paths can apply only to one host, while other paths do the other. Similar to [`CompositeApplication`](https://github.com/michael-lazar/jetforce/blob/master/examples/vhost.py) in Jetforce.

**Comment by pitr** [comment]
Gig apps can be combined using ServerGemini function. So you can do something like this:

```go
apps := map[string]*gig.Gig{}

// App A

a := gig.Default()
apps["app-a.example.com"] = a

a.Handle("/", func(c gig.Context) error {
    return c.Gemini("I am App A")
})

// App B

b := gig.Default()
apps["app-b.example.com"] = b

b.Handle("/", func(c gig.Context) error {
    return c.Gemini("I am App B")
})

// Server
g := gig.New()
g.Handle("/*", func(c gig.Context) error {
    app := apps[c.URL().Host]

    if app == nil {
        return gig.ErrNotFound
    } else {
        return app.ServeGemini(c)
    }
})

g.Run("my.crt", "my.key") // must be wildcard SSL certificate
```

I will add this example to README if it makes sense

**Comment by makeworld-the-better-one** [comment]
This looks like a great example, thanks! And yeah, I think adding it to the README would be a good idea.
