### ISSUE TITLE
"Serving static files" not working as advertised

### ISSUE THREAD

**Issue by Salty2021** [pitr/gig#9]
### Issue Description

The following method of serving static file

```go
g.Static("/test.txt", "content/test.txt")
```
does not seem to work.

### Checklist

- [x] Dependencies installed
- [x] No typos
- [x] Searched existing issues and docs

### Expected behaviour

Server running on localhost. When client requests `gemini://localhost/test.txt`, the server shall return the content of the text file located at `content/test.txt`. The directory structure used is as follows:

```
--$GOPATH (dir)
       |--src (dir)
             |--gig_server (dir)
                    |--content (dir)
                    |       |--test.txt
                    |       |--imgs (dir)
                    |                 |--tuxedo_cat.jpg
                    |--main.go
                    |--go.mod
                    |--gig_server (executable)
                    |--my.crt
                    |--my.key
```

### Actual behaviour

The server returns "not found", and logs the following

```
time="2021-06-18T06:09:03+00:00" path=/test.txt status=51 duration=0.06 error=Not Found
```

### Steps to reproduce

As described above.

### Working code to debug

content of main.go:
```go
package main

import "github.com/pitr/gig"

func main() {
        g := gig.Default()

        g.Static("/test.txt", "content/test.txt")

        g.Run("my.crt", "my.key")
}
```
content of test.txt:
```
Come find me!
```

### Version/commit

go version go1.16.5 darwin/amd64. 
gig version 0.9.8

### Note:

When the "static file" designated is a directory, it works fine. e.g.,

```go
g.Static("/imgs", "content/imgs")
```
works when client requests ``gemini://localhost/imgs/tuxedo_cat.jpg``.

**Comment by pitr** [comment]
This is an error in documentation, `Static` is for folders, `File` is for files. Ie. `g.File("/test.txt", "content/test.txt")` is what you want, I will update the documentation. Thanks for noticing.

**Comment by pitr** [comment]
I clarified [Static section](https://github.com/pitr/gig#serving-static-files) in README. To serve single files, you need to use `g.File` instead. `Static("/test.txt",...)` registers `/test.txt/*`.
